name: bag_it
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8

#state Management
  provider: ^6.1.2

  #Google Fonts for custom fonts
  google_fonts: ^6.2.1

  #Loader
  modal_progress_hud_nsn: ^0.5.1

  #Customization of navigation bar
  curved_navigation_bar: ^1.0.6

  #firebase Operations
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  carousel_slider: ^5.0.0



dev_dependencies:

  #for Changing default icon launcher
  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/on_boarding_delivery.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
